### ISSUE TITLE
How do style the read only ranges?

### ISSUE THREAD

**Issue by snicol21** [andrebnassis/codemirror-readonly-ranges#8]
I absolutely love this library and it's working perfectly for my use case. Thank you for putting this together. Wondering if you have some insight into how I might be able to tweak the background color of the ranges that are read only. I don't see any classes being applied with this extension.

**Comment by stefanreimers** [comment]
This is a quite old issue. Anyway I would like to share my solution, perhaps it might help someone in the future.

Had the same thoughts. As there are no hints in the markup I used CSS. That might be a viable way when 
a. your readonly ranges are at the top and/or the bottom of your code and 
b. you know the number of lines that are readonly.

Let's review an example.

When the code is 
```javascript
class A extends B {
   constructor(){}
   greet(){
      //Your code here
   }
}
```

then the readonly ranges are lines 1 to 3 and 5 to 6. Configuration of the readonly extension might look like this:
```javascript
const getReadOnlyRanges = (targetState:EditorState):Array<{from:number|undefined, to:number|undefined}> => {
    return [
      {
     from: undefined, //same as targetState.doc.line(0).from or 0
     to: targetState.doc.line(3).to
    },
    {
      from: targetState.doc.line(5).from, 
      to: undefined // same as targetState.doc.line(targetState.doc.lines).to
    }
    ]
  }
```

Then you can apply CSS declarations to the editor like this:
```css
.cm-content .cm-line:nth-last-child(-n + 2),
.cm-content .cm-line:nth-child(-n + 3) { 
   background-color: #fafafa !important 
}
/* or */

.cm-content .cm-line:nth-last-child(-n + ${footer.split('\n').length}),
.cm-content .cm-line:nth-child(-n + ${header.split('\n').length}) { 
   background-color: #fafafa !important 
}
```
